# Generated by Django 3.1.3 on 2020-11-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20201112_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinemeeting',
            name='end_time',
            field=models.DateTimeField(db_index=True, max_length=5, verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='onlinemeeting',
            name='start_time',
            field=models.DateTimeField(db_index=True, max_length=5, verbose_name='start_time'),
        ),
    ]
